### ISSUE TITLE
Unorderd_map examples does not compile with Kokkos 4.5.1

### ISSUE THREAD

**Issue by diehlpk** [kokkos/kokkos-tutorials#117]
```
-- Found Kokkos: /home/diehlpk/opt/kokkos-grace/lib64/cmake/Kokkos (version "4.5.1")
-- Configuring done (0.1s)
-- Generating done (0.1s)
-- Build files have been written to: /vast/home/diehlpk/git/kokkos-tutorials/build/Exercises/tasking/Begin
[ 50%] Building CXX object CMakeFiles/Tasking.dir/tasking_begin.cpp.o
/vast/home/diehlpk/git/kokkos-tutorials/Exercises/tasking/Begin/tasking_begin.cpp(98): error: namespace "Kokkos" has no member "TaskScheduler"
      using scheduler_type = Kokkos::TaskScheduler<execution_space>;
                                     ^

/vast/home/diehlpk/git/kokkos-tutorials/Exercises/tasking/Begin/tasking_begin.cpp(98): error: expected a ";"
      using scheduler_type = Kokkos::TaskScheduler<execution_space>;
                                                  ^

/vast/home/diehlpk/git/kokkos-tutorials/Exercises/tasking/Begin/tasking_begin.cpp(99): error: a class or namespace qualified name is required
      using memory_space = typename scheduler_type::memory_space;
                                    ^

/vast/home/diehlpk/git/kokkos-tutorials/Exercises/tasking/Begin/tasking_begin.cpp(99): error: expected a ";"
      using memory_space = typename scheduler_type::memory_space;
                                                  ^

/vast/home/diehlpk/git/kokkos-tutorials/Exercises/tasking/Begin/tasking_begin.cpp(100): error: a class or namespace qualified name is required
      using memory_pool = typename scheduler_type::memory_pool;
                                   ^

/vast/home/diehlpk/git/kokkos-tutorials/Exercises/tasking/Begin/tasking_begin.cpp(100): error: expected a ";"
      using memory_pool = typename scheduler_type::memory_pool;
                                                 ^

/vast/home/diehlpk/git/kokkos-tutorials/Exercises/tasking/Begin/tasking_begin.cpp(105): error: namespace "Kokkos" has no member "BasicFuture"
      Kokkos::BasicFuture<int, scheduler_type> result;
              ^

/vast/home/diehlpk/git/kokkos-tutorials/Exercises/tasking/Begin/tasking_begin.cpp(105): error: type name is not allowed
      Kokkos::BasicFuture<int, scheduler_type> result;
                          ^

/vast/home/diehlpk/git/kokkos-tutorials/Exercises/tasking/Begin/tasking_begin.cpp(105): error: type name is not allowed
      Kokkos::BasicFuture<int, scheduler_type> result;
                               ^

/vast/home/diehlpk/git/kokkos-tutorials/Exercises/tasking/Begin/tasking_begin.cpp(105): error: identifier "result" is undefined
      Kokkos::BasicFuture<int, scheduler_type> result;
                                               ^

10 errors detected in the compilation of "/vast/home/diehlpk/git/kokkos-tutorials/Exercises/tasking/Begin/tasking_begin.cpp".
gmake[2]: *** [CMakeFiles/Tasking.dir/build.make:76: CMakeFiles/Tasking.dir/tasking_begin.cpp.o] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/Tasking.dir/all] Error 2
```

**Comment by masterleinad** [comment]
What does `Unorderd_map` have to do with `Exercises/tasking/Begin/tasking_begin.cpp`? Also these classes should still exist with `Kokkos_ENABLE_DEPRECATED_CODE=ON`.

**Comment by diehlpk** [comment]
I would recommend to remove the example since we will deprecate tasking.
