### ISSUE TITLE
scatter view fails to compile with Kokkos 4.5.1

### ISSUE THREAD

**Issue by diehlpk** [kokkos/kokkos-tutorials#119]
```
-- kokkos_launch_compiler is enabled globally. C++ compiler commands with -DKOKKOS_DEPENDENCE will be redirected to the appropriate compiler for Kokkos
-- Found Kokkos: /home/diehlpk/opt/kokkos-grace/lib64/cmake/Kokkos (version "4.5.1")
-- Configuring done (2.6s)
-- Generating done (0.1s)
CMake Warning:
  Manually-specified variables were not used by the project:

    KokkosKernels_ROOT


-- Build files have been written to: /vast/home/diehlpk/git/kokkos-tutorials/build/Exercises/scatter_view/Begin
[ 50%] Building CXX object CMakeFiles/scatterview.dir/scatter_view.cpp.o
/home/diehlpk/opt/kokkos-grace/include/View/Kokkos_ViewLegacy.hpp(929): error: static assertion failed with "Incompatible View copy construction"
      static_assert(Mapping::is_assignable,
      ^
          detected during instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &, std::enable_if_t<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, void> *) [with DataType=int **, Properties=<Kokkos::HostSpace>, RT=int **, RP=<>]" at line 98 of /vast/home/diehlpk/git/kokkos-tutorials/Exercises/scatter_view/Begin/scatter_view.cpp

/home/diehlpk/opt/kokkos-grace/include/View/Kokkos_ViewMapping.hpp(2944): error: static assertion failed with "View assignment must have compatible spaces"
      static_assert(is_assignable_space,
      ^
          detected during:
            instantiation of "void Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::assign(Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::DstType &, const Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::SrcType &, const Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::TrackType &) [with DstTraits=Kokkos::ViewTraits<int **, Kokkos::HostSpace>, SrcTraits=Kokkos::ViewTraits<int **>]" at line 931 of /home/diehlpk/opt/kokkos-grace/include/View/Kokkos_ViewLegacy.hpp
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &, std::enable_if_t<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, void> *) [with DataType=int **, Properties=<Kokkos::HostSpace>, RT=int **, RP=<>]" at line 98 of /vast/home/diehlpk/git/kokkos-tutorials/Exercises/scatter_view/Begin/scatter_view.cpp

/home/diehlpk/opt/kokkos-grace/include/View/Kokkos_ViewMapping.hpp(2954): error: static assertion failed with "View assignment must have compatible layout or have rank <= 1"
      static_assert(
      ^
          detected during:
            instantiation of "void Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::assign(Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::DstType &, const Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::SrcType &, const Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::TrackType &) [with DstTraits=Kokkos::ViewTraits<int **, Kokkos::HostSpace>, SrcTraits=Kokkos::ViewTraits<int **>]" at line 931 of /home/diehlpk/opt/kokkos-grace/include/View/Kokkos_ViewLegacy.hpp
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &, std::enable_if_t<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, void> *) [with DataType=int **, Properties=<Kokkos::HostSpace>, RT=int **, RP=<>]" at line 98 of /vast/home/diehlpk/git/kokkos-tutorials/Exercises/scatter_view/Begin/scatter_view.cpp

/home/diehlpk/opt/kokkos-grace/include/View/Kokkos_ViewMapping.hpp(3000): error: no instance of constructor "Kokkos::Impl::ViewOffset<Dimension, Kokkos::LayoutRight, std::enable_if_t<<expression>, void>>::ViewOffset [with Dimension=Kokkos::Impl::ViewDimension<0UL, 0UL>]" matches the argument list
            argument types are: (const Kokkos::Impl::ViewOffset<Kokkos::Impl::ViewDimension<0UL, 0UL>, Kokkos::Cuda::array_layout, void>)
      dst.m_impl_offset = dst_offset_type(src.m_impl_offset);
                          ^
/home/diehlpk/opt/kokkos-grace/include/View/Kokkos_ViewMapping.hpp(1818): note #3322-D: number of parameters of function template "Kokkos::Impl::ViewOffset<Dimension, Kokkos::LayoutRight, std::enable_if_t<<expression>, void>>::ViewOffset(const Kokkos::Impl::ViewOffset<DimRHS, Kokkos::LayoutRight, void> &, const Kokkos::Impl::SubviewExtents<DimRHS::rank, 2U> &) [with Dimension=Kokkos::Impl::ViewDimension<0UL, 0UL>]" does not match the call
    __attribute__((device)) __attribute__((host)) inline constexpr ViewOffset(
                                                                   ^
/home/diehlpk/opt/kokkos-grace/include/View/Kokkos_ViewMapping.hpp(1789): note #3327-D: candidate function template "Kokkos::Impl::ViewOffset<Dimension, Kokkos::LayoutRight, std::enable_if_t<<expression>, void>>::ViewOffset(const Kokkos::Impl::ViewOffset<DimRHS, Kokkos::LayoutStride, void> &) [with Dimension=Kokkos::Impl::ViewDimension<0UL, 0UL>]" failed deduction
    __attribute__((device)) __attribute__((host)) inline ViewOffset(
                                                         ^
/home/diehlpk/opt/kokkos-grace/include/View/Kokkos_ViewMapping.hpp(1778): note #3327-D: candidate function template "Kokkos::Impl::ViewOffset<Dimension, Kokkos::LayoutRight, std::enable_if_t<<expression>, void>>::ViewOffset(const Kokkos::Impl::ViewOffset<DimRHS, Kokkos::LayoutRight, void> &) [with Dimension=Kokkos::Impl::ViewDimension<0UL, 0UL>]" failed deduction
    __attribute__((device)) __attribute__((host)) inline constexpr ViewOffset(
                                                                   ^
/home/diehlpk/opt/kokkos-grace/include/View/Kokkos_ViewMapping.hpp(1768): note #3322-D: number of parameters of function template "Kokkos::Impl::ViewOffset<Dimension, Kokkos::LayoutRight, std::enable_if_t<<expression>, void>>::ViewOffset(const std::integral_constant<unsigned int, TrivialScalarSize> &, const Kokkos::LayoutRight &) [with Dimension=Kokkos::Impl::ViewDimension<0UL, 0UL>]" does not match the call
    __attribute__((device)) __attribute__((host)) inline constexpr ViewOffset(
                                                                   ^
/home/diehlpk/opt/kokkos-grace/include/View/Kokkos_ViewMapping.hpp(1743): note #3326-D: function "Kokkos::Impl::ViewOffset<Dimension, Kokkos::LayoutRight, std::enable_if_t<<expression>, void>>::ViewOffset(const Kokkos::Impl::ViewOffset<Dimension, Kokkos::LayoutRight, std::enable_if_t<<expression>, void>> &) [with Dimension=Kokkos::Impl::ViewDimension<0UL, 0UL>]" does not match because argument #1 does not match parameter
    ViewOffset(const ViewOffset&) = default;
    ^
/home/diehlpk/opt/kokkos-grace/include/View/Kokkos_ViewMapping.hpp(1742): note #3322-D: number of parameters of function "Kokkos::Impl::ViewOffset<Dimension, Kokkos::LayoutRight, std::enable_if_t<<expression>, void>>::ViewOffset() [with Dimension=Kokkos::Impl::ViewDimension<0UL, 0UL>]" does not match the call
    ViewOffset() = default;
    ^
          detected during:
            instantiation of "void Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::assign(Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::DstType &, const Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::SrcType &, const Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::TrackType &) [with DstTraits=Kokkos::ViewTraits<int **, Kokkos::HostSpace>, SrcTraits=Kokkos::ViewTraits<int **>]" at line 931 of /home/diehlpk/opt/kokkos-grace/include/View/Kokkos_ViewLegacy.hpp
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &, std::enable_if_t<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, void> *) [with DataType=int **, Properties=<Kokkos::HostSpace>, RT=int **, RP=<>]" at line 98 of /vast/home/diehlpk/git/kokkos-tutorials/Exercises/scatter_view/Begin/scatter_view.cpp

/home/diehlpk/opt/kokkos-grace/include/View/Kokkos_ViewLegacy.hpp(929): error: static assertion failed with "Incompatible View copy construction"
      static_assert(Mapping::is_assignable,
      ^
          detected during instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &, std::enable_if_t<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, void> *) [with DataType=int *, Properties=<Kokkos::HostSpace>, RT=int *, RP=<>]" at line 98 of /vast/home/diehlpk/git/kokkos-tutorials/Exercises/scatter_view/Begin/scatter_view.cpp

/home/diehlpk/opt/kokkos-grace/include/View/Kokkos_ViewMapping.hpp(2944): error: static assertion failed with "View assignment must have compatible spaces"
      static_assert(is_assignable_space,
      ^
          detected during:
            instantiation of "void Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::assign(Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::DstType &, const Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::SrcType &, const Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::TrackType &) [with DstTraits=Kokkos::ViewTraits<int *, Kokkos::HostSpace>, SrcTraits=Kokkos::ViewTraits<int *>]" at line 931 of /home/diehlpk/opt/kokkos-grace/include/View/Kokkos_ViewLegacy.hpp
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &, std::enable_if_t<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, void> *) [with DataType=int *, Properties=<Kokkos::HostSpace>, RT=int *, RP=<>]" at line 98 of /vast/home/diehlpk/git/kokkos-tutorials/Exercises/scatter_view/Begin/scatter_view.cpp

```

**Comment by masterleinad** [comment]
What's the configuration you are using?

**Comment by diehlpk** [comment]
Kokkos with Serial, OpenMP, and CUDA enabled on Grace Hopper with Cuda 12.5 and gcc 12.3.
